# Generated by Django 5.1.2 on 2025-04-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'company',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='fish',
            options={'managed': True, 'verbose_name_plural': 'fishes'},
        ),
        migrations.AlterField(
            model_name='fish',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fishbase',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fishbase',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fishbase',
            name='entry_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fishbase',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fishbase',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fishbase',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fishbase',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
