# Generated by Django 5.1.2 on 2025-04-17 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_date_joined_alter_user_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FishInBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fish_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.fishbase"
                    ),
                ),
                (
                    "fish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.fish"
                    ),
                ),
                (
                    "price_per_kilo",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "unique_together": {("fish_base", "fish")},
            },
        ),
        migrations.AddField(
            model_name="fishbase",
            name="fishes",
            field=models.ManyToManyField(
                related_name="bases", through="api.FishInBase", to="api.fish"
            ),
        ),
    ]
