# Generated by Django 5.1.2 on 2025-05-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fishingsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='fish',
            options={'verbose_name_plural': 'fishes'},
        ),
        migrations.AlterModelOptions(
            name='fishbase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='staffprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='fishinbase',
            table='fish_in_base',
        ),
        migrations.AlterModelTable(
            name='fishingsession',
            table='fishing_session',
        ),
    ]
