# Generated by Django 5.1.2 on 2025-04-17 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fishinbase_fishbase_fishes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishbase',
            name='fish_in_base',
        ),
    ]
