# Generated by Django 5.1.2 on 2025-05-01 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_company_options_alter_fish_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishingsession',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
