# Generated by Django 5.1.2 on 2025-04-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_fishes_fishbase_fish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishbase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fish_base_images'),
        ),
    ]
